# Site settings
title: heliosapollo
header-img: img/home-bg.jpg
email: helios.apollo.blog@gmail.com
description: "Tehnologija, filozofija, obrazovanje, umetnost"
baseurl: ""
url: "http://helios-apollo.github.io"
github_username:  helios-apollo

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
